### PR TITLE
Design Fixes: footer-archive.html template

### LINKED ISSUE #155: footer banner missing edge padding
https://wordpress.org/news-test/category/community/ mobile - footer banner doesn't have edge padding anymore. still works on homepage, but not categories, search, 404, etc. maybe related to #123 

(copied from #128)

### LINKED ISSUE #158: Dark footer link text needs better contrast
Ex, on the Releases page. The regular text switches to white, but the link text is the same blue & does not have enough contrast against the dark background.

Screen Shot 2022-01-06 at 5 31 34 PM

### PR DESCRIPTION
**Pull request by shaunandrews**
This PR fixed a few things with the `footer-archive` template part:

- Ensures the correct spacing on both light and dark variants along with the front-page and category-archive templates.
- Adjusts the brush stroke (behind the "Listen to all...") for the dark variant.
- Adjusts the link colors (including social-icon SVGs) for the dark variant.
- Reduces the size of, and the gap between, social-link blocks to help avoid wrapping the "Listen to all..." link.

Before:

footer-before

After:

footer-after

Fixes #155 and #158

### CODE REVIEW

**Comment by ryelle** [comment]
How can I see the dark footer?

**Comment by shaunandrews** [comment]
Oh, sorry. I added the issue (#155) that explains it. You go into a category archive (like `/category/releases/`) and the bottom area goes dark.

**Comment by shaunandrews** [comment]
Well, I guess this doesn't actually resolve #155 fully. I only fixed it for the dark variant. I'll do the light variant tomorrow.

**Comment by beafialho** [comment]
Thanks @shaunandrews! 

I have a couple comments:

- the links color in dark backgrounds should be Blue 3 `#7B90FF` to pass color contrast checks, instead of Blue 1 `#3E58E1`.
- the "After" screenshot doesn't show the Subscribe bar, but from the "Before" screenshot, it should have a white field, instead of dark, with placeholder text the same size as the button, like this:

Captura de ecrã 2022-01-07, às 10 45 53

**Comment by shaunandrews** [comment]
I did notice the colors being different, but I'm not entirely sure how the colors are defined yet. I'll have to look, but it might be a different PR.

--

The subscribe box is missing because I don't have the block locally. I'm not sure how to get it (its a Jetpack block) but I'll see what I can do to get it working locally so I can fix it.

**Comment by shaunandrews** [comment]
Pushed a handful of updates and things are looking much better. Would love a review.

**Comment by beafialho** [comment]
@shaunandrews could you post a screenshot of the changes?

**Comment by shaunandrews** [comment]
@beafialho I updated the original description with before/after GIFs. Sorry if that wasn't clear.

**Comment by beafialho** [comment]
Oh that's right, I missed that. This looks good to me!

**Comment by ryelle** [comment]
I'm seeing a double-border between rows on the dark footer now:

Screen Shot 2022-01-07 at 3 50 25 PM

Other than that, this looks good and will also close #158.

**Comment by shaunandrews** [comment]
Good eyes, @ryelle — I pushed a fix.

**Review by ryelle — APPROVED** [review]
Looks good now 👍🏻

**Pull request merged**
