### PR TITLE
Headings: Increase specificity of responsive font size ruleset

### PR DESCRIPTION
**Pull request by ryelle**
The headings use different font sizes on large screens vs small screens, and to do that, the CSS overrides the custom properties. At some point, either the specificity or the order of the core-generated properties changed, so that they're overriding our overrides… so this change bumps up our specificity, to make sure our values take effect.

| Before | After |
|---|---|
| before | after |

@beafialho Pinging you to make sure these are the correct sizes now :)

### CODE REVIEW

**Comment by beafialho** [comment]
Thanks @ryelle! I see the correct sizes on large screens but not on small screens.

**Comment by ryelle** [comment]
Is there something wrong with small screens? I thought the font sizes were already correct there?

**Comment by beafialho** [comment]
> Is there something wrong with small screens? I thought the font sizes were already correct there?

Sorry for the confusion, yes they are correct in the smallest screen size 👍 

I thought they would decrease gradually _as_ we resize the window. Correct me if I'm wrong but I think at some point we were using a function to do that?

**Comment by ryelle** [comment]
> I thought they would decrease gradually as we resize the window. Correct me if I'm wrong but I think at some point we were using a function to do that?

It looks like we're only using that function on `h3`s, and it only applies between 650px - 900px wide.

**Comment by beafialho** [comment]
> It looks like we're only using that function on `h3`s, and it only applies between 650px - 900px wide.

I see, this works fine for now. Could we apply it for other headings on a next phase post launch?

**Comment by ryelle** [comment]
Yeah, I think it's a great idea - looks like there's already an issue for post-launch iteration: https://github.com/WordPress/wporg-news-2021/issues/39

**Comment by beafialho** [comment]
> Yeah, I think it's a great idea - looks like there's already an issue for post-launch iteration: #39

That's right, I kept thinking there was a convo about it somewhere... Thank you!

**Pull request merged**
