### PR TITLE
Blockquote: spacing + full width alignment fixes

### LINKED ISSUE #141: Blockquote: spacing + full width alignment
Large quotation mark style quotes should go full width. The spacing above them should be `40px` and below them `90px`

**Currently:**

Captura de ecrã 2021-12-20, às 16 02 12

**Intended:**

Captura de ecrã 2021-12-20, às 16 08 27

Captura de ecrã 2021-12-20, às 16 08 03

### PR DESCRIPTION
**Pull request by MaggieCabrera**
Closes https://github.com/WordPress/wporg-news-2021/issues/141

I also changed the color of the cite and the size of the quotes on mobile to fit the design.

Screenshot 2022-01-20 at 12 48 06

### CODE REVIEW

**Comment by beafialho** [comment]
Thanks @MaggieCabrera, it looks great both on desktop and on mobile.

Any idea why I'm seeing all quotes in `Bold`?

Captura de ecrã 2022-01-20, às 12 27 26

**Comment by MaggieCabrera** [comment]
> Thanks @MaggieCabrera, it looks great both on desktop and on mobile.
> 
> Any idea why I'm seeing all quotes in `Bold`?

Because they are set to bold on the editor, you can edit the post and change that, I'm not sure we should override that

**Review by iandunn — APPROVED** [review]
LGTM 👍🏻

**Comment by iandunn** [comment]
I'm gonna go ahead and merge this to lock in the approved bits. @beafialho , if you'd like to do something about the bold issue, can you open a new issue?

**Comment by beafialho** [comment]
I did open one #140 about that

**Comment by ryelle** [comment]
The fix for #140 only applied to the quote block, not the pullquote block. I'll re-open it for bold + pullquotes too.

**Comment by beafialho** [comment]
Ah, sorry.. I should have mentioned pullquote too!

**Pull request merged**
